version: '3.8'

services:

  backend:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/backend
    env_file: .env
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    image: postgres:15.3
    ports:
      - 127.0.0.1:5432:5432

  redis:
    image: redis:7.2.4
    ports:
      - 127.0.0.1:${REDIS_PORT}:${REDIS_PORT}

  rabbitmq:
    image: rabbitmq:3.12.13-alpine
    ports:
      - 127.0.0.1:${RABBITMQ_PORT}:${RABBITMQ_PORT}
    environment:
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  celery_worker:
    build: .
    command: celery -A src.celery.worker worker --loglevel=info
    env_file: .env
    volumes:
      - .:/backend
    stdin_open: true
    tty: true
    depends_on:
      - db
      - rabbitmq
