"""empty message

Revision ID: faab1915f015
Revises: e9bd7c60fa81
Create Date: 2024-03-30 22:34:50.733693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faab1915f015'
down_revision = 'e9bd7c60fa81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
