"""empty message

Revision ID: d6b039d06eae
Revises: faab1915f015
Create Date: 2024-03-30 22:35:58.418212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b039d06eae'
down_revision = 'faab1915f015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
