"""empty message

Revision ID: b5679f8aca13
Revises: 2ed93cf94106
Create Date: 2024-03-31 16:18:14.764340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5679f8aca13'
down_revision = '2ed93cf94106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
