"""empty message

Revision ID: 2ed93cf94106
Revises: 24ebee84c1a7
Create Date: 2024-03-31 16:17:58.223569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed93cf94106'
down_revision = '24ebee84c1a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
