"""empty message

Revision ID: e274698be40c
Revises: 39d6f1d12c65
Create Date: 2024-04-04 06:41:51.175393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e274698be40c'
down_revision = '39d6f1d12c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
